// Generated by SugarLisp v0.6.5
var sl = require('sugarlisp-core/sl-types');
var match = require('sugarlisp-match/pattern-match');

function fib(x) {
  return match([
    x
  ], function(when) {
    when([
        0
      ],
      function(vars) {
        return 0;
      }, this);
    when([
        1
      ],
      function(vars) {
        return 1;
      }, this);
    when([
        match.var("x", match.any)
      ],
      function(vars) {
        return (function(x) {
          return (fib(x - 1) + fib(x - 2));
        }).call(this, vars["x"]);
      }, this);
  }, this);

}
console.log(fib(8));